plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - index.md
markdown: GFM
theme: jekyll-theme-midnight
title: Breanna Shi
description: Applied Mathematician, Computer scientist, Bioinformatician, Georgia Tech PhD Student
