plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - index.md
markdown: GFM
theme: jekyll-theme-midnight
  features:
    - navigation.tabs
title: Breanna Shi
description: Applied Mathematician, Computer scientist, Bioinformatician, Georgia Tech PhD Student
nav:
  - Section:
    - section/index.md
    - Page 1: section/page-1.md
    - Page n: section/page-n.md
