plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - index.md
markdown: GFM
theme: jekyll-theme-midnight
title: The title
description: Description
